### ISSUE TITLE
小程序码转url？

### ISSUE THREAD

**Issue by Usernamezhx** [Jon-Millent/miniprogram-qrcode#1]
你好，这个目前腾讯暂时不支持码

**Comment by Jon-Millent** [comment]
暂时还没有小程序码转url的功能吧

**Comment by Usernamezhx** [comment]
@Jon-Millent 你好 我现在想做这件事，在图库中找到小程序码，然后和本地的小程序码对比，或者说现在是否有这样的api 调用传入图片，返回该小程序码的唯一标识，这样我就可以做比对了。谢谢
